kind: Deployment
apiVersion: apps/v1
metadata:
  name: sonarqube
  namespace: sonarqube
  annotations:
    deployment.kubernetes.io/revision: '4'
spec:
  replicas: 9
  selector:
    matchLabels:
      name: sonarqube
  template:
    metadata:
      name: sonarqube
      creationTimestamp: null
      labels:
        name: sonarqube
    spec:
      initContainers:
        - name: sysctl
          image: busybox
          command:
            - sysctl
            - '-w'
            - vm.max_map_count=262144
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
      containers:
        - name: sonarqube
          image: 'sonarqube:7.9.1-community'
          ports:
            - name: sonarqube
              containerPort: 9000
              protocol: TCP
          env:
            - name: SONARQUBE_JDBC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-pwd
                  key: password
            - name: SONARQUBE_JDBC_URL
              value: 'jdbc:postgresql://sonar-postgres:5432/sonar'
          resources:
            limits:
              memory: 3000Mi
            requests:
              memory: 3000Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 3
  progressDeadlineSeconds: 600