kind: Deployment
apiVersion: apps/v1
metadata:
  name: sonar-postgres
  namespace: sonarqube
  selfLink: /apis/apps/v1/namespaces/sonarqube/deployments/sonar-postgres
  generation: 1
  annotations:
    deployment.kubernetes.io/revision: '1'
spec:
  replicas: 1
  selector:
    matchLabels:
      name: sonar-postgres
  template:
    metadata:
      name: sonar-postgres
      creationTimestamp: null
      labels:
        name: sonar-postgres
    spec:
      volumes:
        - name: data-disk
          persistentVolumeClaim:
            claimName: claim-postgres
      containers:
        - name: sonar-postgres
          image: 'postgres:12.1'
          ports:
            - name: postgresport
              containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-pwd
                  key: password
            - name: POSTGRES_USER
              value: sonar
          resources: {}
          volumeMounts:
            - name: data-disk
              mountPath: /var/lib/postgresql/data
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600