apiVersion: v1
data:
  # base64 kinda string which contains dockerconfig
  .dockerconfigjson: >-
    <base64 docker config string>
kind: Secret
metadata:
  name: ibm-cr-io # region of registry to pick images from 
  namespace: app-listener #Whatever namespace reqd
type: kubernetes.io/dockerconfigjson